apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-microservices
  region: ap-south-1

managedNodeGroups:
  - name: worker-nodes
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4