apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orderService.name }}
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.orderService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orderService.name }}
    spec:
      containers:
      - name: {{ .Values.orderService.name }}
        image: "{{ .Values.image.repository }}/order-service:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.orderService.port }}

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.orderService.port }}
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.orderService.port }}
          initialDelaySeconds: 5
          periodSeconds: 5