apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# mysql
- mysql/secret.yaml
- mysql/pvc.yaml
- mysql/deployment.yaml
- mysql/service.yaml

# user service
- user-service/configmap.yaml
- user-service/deployment.yaml
- user-service/service.yaml
- user-service/hpa.yaml

# order service
- order-service/deployment.yaml
- order-service/service.yaml

# frontend
- frontend/configmap.yaml
- frontend/deployment.yaml
- frontend/service.yaml