name: Deploy Microservices to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/frontend:${{ env.IMAGE_TAG }} ./services/frontend
          docker push ${{ env.ECR_REGISTRY }}/frontend:${{ env.IMAGE_TAG }}

      - name: Build and Push User Service
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/user-service:${{ env.IMAGE_TAG }} ./services/user-service
          docker push ${{ env.ECR_REGISTRY }}/user-service:${{ env.IMAGE_TAG }}

      - name: Build and Push Order Service
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/order-service:${{ env.IMAGE_TAG }} ./services/order-service
          docker push ${{ env.ECR_REGISTRY }}/order-service:${{ env.IMAGE_TAG }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install microservices ./microservices \
          --set frontend.image=${{ env.ECR_REGISTRY }}/frontend:${{ env.IMAGE_TAG }} \
          --set userService.image=${{ env.ECR_REGISTRY }}/user-service:${{ env.IMAGE_TAG }} \
          --set orderService.image=${{ env.ECR_REGISTRY }}/order-service:${{ env.IMAGE_TAG }} \
          --atomic \
          --timeout 5m

#      - name: Deploy to Kubernetes
#        run: |
#          kubectl set image deployment/frontend \
#            frontend=${{ env.ECR_REGISTRY }}/frontend:${{ env.IMAGE_TAG }}
#          
#          kubectl set image deployment/user-service \
#            user-service=${{ env.ECR_REGISTRY }}/user-service:${{ env.IMAGE_TAG }}
#          
#          kubectl set image deployment/order-service \
#            order-service=${{ env.ECR_REGISTRY }}/order-service:${{ env.IMAGE_TAG }}